const ACTIVITIES = {
  transport: [
    { id: 'car',     name: 'Car (petrol)',      emoji: '🚗', unit: 'km',        factor: 0.21,  color: '#ef4444',
      tip: 'Carpooling with just one person halves your per-km emissions. Switching 2 days/week to public transport cuts transport footprint by ~30%.',
      save: '~2.5 kg/day', diff: 'High impact' },
    { id: 'bike',    name: 'Motorbike',          emoji: '🏍️', unit: 'km',        factor: 0.11,  color: '#f97316',
      tip: 'Electric two-wheelers (like Ola S1) emit ~90% less CO₂ per km and cost ₹1–2/km vs ₹4–5/km for petrol bikes.',
      save: '~1.2 kg/day', diff: 'Medium impact' },
    { id: 'auto',    name: 'Auto rickshaw (CNG)',emoji: '🛺', unit: 'km',        factor: 0.08,  color: '#f59e0b',
      tip: 'CNG autos are already a relatively clean choice! Electric autos, where available, emit ~70% less.',
      save: '~0.5 kg/day', diff: 'Low impact' },
    { id: 'bus',     name: 'City bus',            emoji: '🚌', unit: 'km',        factor: 0.089, color: '#84cc16',
      tip: 'Buses emit 4–6× less per passenger-km than a solo petrol car. Great choice for regular commutes.',
      save: '~0.4 kg/day', diff: 'Low impact' },
    { id: 'metro',   name: 'Metro / train',       emoji: '🚆', unit: 'km',        factor: 0.041, color: '#22c55e',
      tip: 'Metro rail is one of the cleanest urban transport options — about 5× cleaner than a petrol car per km.',
      save: '~0.2 kg/day', diff: 'Very low' },
    { id: 'flight',  name: 'Flight',              emoji: '✈️', unit: 'km',        factor: 0.255, color: '#dc2626',
      tip: 'A single 1000 km flight emits ~255 kg CO₂ — equal to 3 weeks of average daily emissions. Consider trains for trips under 600 km.',
      save: '~5+ kg/trip', diff: 'Very high impact' },
  ],
  home: [
    { id: 'elec',    name: 'Electricity',         emoji: '⚡', unit: 'kWh',       factor: 0.82,  color: '#f59e0b',
      tip: '5-star rated ACs, refrigerators, and washing machines use 30–40% less electricity. LED bulbs use 80% less than incandescent.',
      save: '~1.6 kg/day', diff: 'High impact' },
    { id: 'lpg',     name: 'LPG cooking gas',     emoji: '🔥', unit: 'cylinders', factor: 14.2,  color: '#ef4444',
      tip: 'Induction cooktops convert ~85% of energy to heat vs ~40% for gas. Switching saves both money and emissions over time.',
      save: '~2.8 kg/cook', diff: 'Medium impact' },
    { id: 'ac',      name: 'Air conditioning',    emoji: '❄️', unit: 'hours',     factor: 0.5,   color: '#3b82f6',
      tip: 'Raising your AC thermostat from 18°C to 24°C saves 24% electricity per degree. Clean filters monthly for 5–10% efficiency gains.',
      save: '~1 kg/day', diff: 'Medium impact' },
    { id: 'geyser',  name: 'Electric geyser',     emoji: '🚿', unit: 'hours',     factor: 0.9,   color: '#8b5cf6',
      tip: 'Solar water heaters (cost ₹15–25K) eliminate geyser emissions and pay back in 3–5 years through electricity savings.',
      save: '~0.9 kg/day', diff: 'Medium impact' },
    { id: 'fan',     name: 'Ceiling fans',         emoji: '🌀', unit: 'hours',     factor: 0.04,  color: '#06b6d4',
      tip: 'BEE 5-star fans use ~30W vs older 75W fans. Running fans only when in the room saves significant electricity.',
      save: '~0.1 kg/day', diff: 'Low impact' },
  ],
  food: [
    { id: 'beef',    name: 'Beef / mutton',        emoji: '🥩', unit: 'servings',  factor: 3.3,   color: '#dc2626',
      tip: 'One beef serving generates as much CO₂ as driving 16 km. Replacing with lentils (dal) twice a week saves ~6.6 kg CO₂.',
      save: '~3.3 kg/meal', diff: 'Very high impact' },
    { id: 'chicken', name: 'Chicken / eggs',        emoji: '🍗', unit: 'servings',  factor: 0.72,  color: '#f97316',
      tip: 'Chicken has 5× lower impact than beef. Eggs (0.5 kg each) are even more efficient protein sources.',
      save: '~0.5 kg/meal', diff: 'Medium impact' },
    { id: 'dairy',   name: 'Dairy (milk, curd)',    emoji: '🥛', unit: 'servings',  factor: 0.6,   color: '#f59e0b',
      tip: 'Local cooperative dairy has lower transport emissions. Oat milk emits ~70% less than cow\'s milk if you want to try plant-based.',
      save: '~0.4 kg/serving', diff: 'Low impact' },
    { id: 'veg',     name: 'Vegetables / dal',      emoji: '🥗', unit: 'servings',  factor: 0.15,  color: '#22c55e',
      tip: 'Plant-based meals are the single highest-impact dietary switch. Seasonal local vegetables have even lower footprints.',
      save: 'Already low!', diff: 'Very low' },
    { id: 'rice',    name: 'Rice',                  emoji: '🍚', unit: 'kg cooked', factor: 2.7,   color: '#eab308',
      tip: 'Rice paddies emit methane during flooding. Choosing alternate-wetting cultivation reduces rice emissions by up to 50%.',
      save: '~0.8 kg/kg', diff: 'Medium impact' },
    { id: 'processed', name: 'Packaged / processed food', emoji: '🍟', unit: 'servings', factor: 1.4, color: '#f97316',
      tip: 'Ultra-processed foods involve high-energy manufacturing and long-distance supply chains. Fresh local food cuts this significantly.',
      save: '~1 kg/serving', diff: 'Medium impact' },
  ],
  shopping: [
    { id: 'clothes', name: 'New clothing item',     emoji: '👕', unit: 'items',     factor: 10.0,  color: '#ec4899',
      tip: 'Fashion has one of the highest per-item emissions. Buying second-hand, repairing clothes, or choosing quality over quantity makes a big difference.',
      save: '~8 kg/item', diff: 'Very high impact' },
    { id: 'phone',   name: 'New electronics',       emoji: '📱', unit: 'items',     factor: 70.0,  color: '#8b5cf6',
      tip: 'A smartphone accounts for ~70 kg CO₂ to manufacture. Extending your phone\'s life by 1 year halves its annual carbon cost.',
      save: '~35 kg/year', diff: 'High impact' },
    { id: 'online',  name: 'Online deliveries',     emoji: '📦', unit: 'orders',    factor: 0.5,   color: '#06b6d4',
      tip: 'Batching orders reduces delivery trips. Choosing slower shipping is often more efficient than express delivery.',
      save: '~0.3 kg/order', diff: 'Low impact' },
    { id: 'plastic', name: 'Single-use plastic',    emoji: '🧴', unit: 'items',     factor: 0.2,   color: '#ef4444',
      tip: 'Beyond CO₂, plastic pollutes ecosystems for centuries. Reusable bags, bottles, and containers eliminate this entirely.',
      save: '~0.2 kg/item', diff: 'Low impact' },
  ]
};

const INDIA_AVG = 4.8;
const WORLD_AVG = 12.0;
const US_AVG    = 47.0;
